config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:new, :create]
  resource :session, only: [:new, :create, :destroy]
  resources :games, only: [:index]
  resource :highscore, only: [:create]

  root "games#index"
end

app/models/highscore.rb
class Highscore < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
require 'bcrypt'

class User < ActiveRecord::Base
  attr_reader :password

  validates :username, :password_digest, :session_token, presence: true
  validates :password, length: { minimum: 6, allow_nil: true }
  validates :session_token, uniqueness: true
  before_validation :ensure_session_token

  has_many :highscores

  def self.find_by_credentials(username, password)
    user = User.find_by(username: username)
    (user && user.is_password?(password)) ? user : nil
  end

  def reset_session_token!
    self.session_token = SecureRandom::urlsafe_base64(16)
    save!
    session_token
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(password_digest).is_password?(password)
  end

  def ensure_session_token
    self.session_token ||= SecureRandom::urlsafe_base64(16)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    User.find_by(session_token: session[:session_token])
  end

  protected
  def redirect_if_logged_in
    redirect_to :root if current_user
  end

  def redirect_if_logged_out
    redirect_to new_session_url unless current_user
  end

  def log_in!(user)
    session[:session_token] = user.reset_session_token!
  end

  def log_out!
    current_user.reset_session_token!
    session[:session_token] = nil
  end

  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :redirect_if_logged_out

  def index
    @highscores = Highscore.all
    render :index
  end
end

app/controllers/highscores_controller.rb
class HighscoresController < ApplicationController
  def create
    Highscore.create!(score: params[:score], user_id: current_user.id)
    until Highscore.all.length == 5
      Highscore.order(:score).limit(1)[0].destroy
    end
    render json: Highscore.all.to_json
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :redirect_if_logged_in, only: [:new, :create]

  def new
    @user = User.new
    render :new
  end

  def create
    user = User.find_by_credentials(params[:user][:username],
      params[:user][:password])
    if user
      log_in!(user)
      redirect_to :root
    else
      @user = User.new(user_params)
      flash.now[:errors] = ["Invalid Username/Password"]
      render :new
    end
  end

  def destroy
    log_out!
    redirect_to new_session_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :redirect_if_logged_in

  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in!(@user)
      redirect_to :root
    else
      render :new
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def csrf_token
   "<input type='hidden' name='authenticity_token' value='#{form_authenticity_token}'>".html_safe
   end

   def error_messages(model)
    return "" unless model.errors.full_messages
    html = "<div><ul>"
    model.errors.full_messages.each do |msg|
      html += "<li>#{h(msg)}</li>"
    end
    if flash[:errors]
      flash[:errors].each do |msg|
        html += "<li>#{h(msg)}</li>"
      end
    end
    html += "</ul></div>"
    html.html_safe
  end
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/highscores_helper.rb
module HighscoresHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/games/index.html.erb
<h1>Tetris</h1>

<div class="tetris cf">
  <div class="highscores">
    <span>Hishscores:</span>
    <ul>
      <li>Russell: 500</li>
      <li>Gage: 460</li>
      <li>Guru: 210</li>
      <li>Sam: 110</li>
      <li>Wil: 30</li>
    </ul>
  </div>

  <ul class="board cf">
  </ul>

  <div class="info-pane">
    <span class="score">Score: 160</span>
    <h2>next:</h2>
    <ul class="next cf">
    </ul>
    <h2>save:</h2>
    <ul class="save cf">
    </ul>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tetris</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<header class="cf">
<% if current_user %>
  <span>Logged In As: <%= current_user.username %></span>
  <%= button_to "Log Out", session_url, method: :delete %>
<% else %>
  <%= button_to "Log In", new_session_url, method: :get %>
  <%= button_to "Sign Up", new_user_url, method: :get %>
<% end %>
</header>

<%= yield %>

</body>
</html>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<div class="user-form">
  <form action="/users" method="post">
    <%= csrf_token %>

    <label for="username">Username:</label>
    <input id="username" type="text" name="user[username]" value="<%= @user.username %>">

    <br><br>

    <label for="password">Password:</label>
    <input id="password" type="password" name="user[password]" value="<%= @user.password %>">

    <br><br>

    <%= error_messages(@user) %>

    <input type="submit" value="Sign Up">
  </form>
</div>